name: sfrmaker_ci
channels:
  - conda-forge
dependencies:
  - python
  - ipython
  - jupyter
  - notebook
  - ipykernel
  - matplotlib
  - pyyaml
  - numpy<2
  - scipy
  - pandas
  - xarray
  - geopandas
  - gdal
  - fiona
  - rasterio
  - rasterstats
  - shapely
  - rtree
  - pyproj
  - netcdf4
  - codecov
  - coverage
  - flake8
  - pytest
  - sphinx
  - numpydoc
  - nbsphinx  # for rendering notebooks in sphinx-generated docs
  - sphinx-copybutton
  - sphinx_rtd_theme
  - pip
  - pip:
    - gis-utils
    - pytest-timeout
    - git+https://github.com/modflowpy/flopy@develop
    - git+https://github.com/aleaf/modflow-export@develop
